In [1]:
#IMPORT DEPENDENCY
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from collections import Counter

import warnings
warnings.filterwarnings('ignore')


from sklearn import tree
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [2]:
#LOAD SOCCER DATA INTO A DATAFRAME
soccer_data_load = "C:/Users/davec/Desktop/Class/20_Final_Project/soccer_data_V2.csv"
soccer_data_df = pd.read_csv(soccer_data_load, encoding = 'unicode_escape')
soccer_data_df.head(10)

team_name  team_code           common_name  season  country  \
0               Arsenal FC          1               Arsenal    2020  England   
1     Tottenham Hotspur FC          2     Tottenham Hotspur    2020  England   
2       Manchester City FC          3       Manchester City    2020  England   
3        Leicester City FC          4        Leicester City    2020  England   
4  West Bromwich Albion FC          5  West Bromwich Albion    2020  England   
5        Crystal Palace FC          6        Crystal Palace    2020  England   
6               Everton FC          7               Everton    2020  England   
7               Burnley FC          8               Burnley    2020  England   
8           Southampton FC          9           Southampton    2020  England   
9     Manchester United FC         10     Manchester United    2020  England   

   country_code  matches_played  matches_played_home  matches_played_away  \
0             1              13                    7                    6   
1             1              13                    6                    7   
2             1              12                    6                    6   
3             1              13                    7                    6   
4             1              13                    6                    7   
5             1              13                    6                    7   
6             1              13                    6                    7   
7             1              12                    5                    7   
8             1              13                    6                    7   
9             1              12                    6                    6   

   suspended_matches  ...  goals_conceded_min_51_to_60  \
0                  0  ...                            0   
1                  0  ...                            2   
2                  1  ...                            3   
3                  0  ...                            0   
4                  0  ...                            6   
5                  0  ...                            1   
6                  0  ...                            1   
7                  1  ...                            0   
8                  0  ...                            3   
9                  1  ...                            1   

   goals_conceded_min_61_to_70  goals_conceded_min_71_to_80  \
0                            0                            4   
1                            0                            0   
2                            1                            2   
3                            0                            2   
4                            5                            1   
5                            1                            2   
6                            1                            2   
7                            6                            3   
8                            2                            3   
9                            1                            2   

   goals_conceded_min_81_to_90  draw_percentage_overall  draw_percentage_home  \
0                            2                     0.15                  0.14   
1                            7                     0.31                  0.33   
2                            1                     0.42                  0.33   
3                            4                     0.00                  0.00   
4                            5                     0.31                  0.33   
5                            5                     0.23                  0.33   
6                            3                     0.15                  0.17   
7                            0                     0.33                  0.20   
8                            4                     0.23                  0.00   
9                            3                     0.17                  0.33   

   draw_percentage_away  loss_percentage_ovearll  loss_percenta

In [3]:
# Drop the null columns where all values are null
soccer_data_null_columns_df = soccer_data_df.dropna(axis='columns', how='all')
soccer_data_null_columns_df

team_name  team_code           common_name  \
0                          Arsenal FC          1               Arsenal   
1                Tottenham Hotspur FC          2     Tottenham Hotspur   
2                  Manchester City FC          3       Manchester City   
3                   Leicester City FC          4        Leicester City   
4             West Bromwich Albion FC          5  West Bromwich Albion   
...                               ...        ...                   ...   
1053           Getafe Club de F?§tbol       1054             Getafe CF   
1054                         Elche CF       1055              Elche CF   
1055  Real Valladolid Club de F?§tbol       1056       Real Valladolid   
1056                        SD Huesca       1057             SD Huesca   
1057                        C?­diz CF       1058                C?­diz   

      season  country  country_code  matches_played  matches_played_home  \
0       2020  England             1              13                    7   
1       2020  England             1              13                    6   
2       2020  England             1              12                    6   
3       2020  England             1              13                    7   
4       2020  England             1              13                    6   
...      ...      ...           ...             ...                  ...   
1053    2020    Spain             5              12                    7   
1054    2020    Spain             5              12                    6   
1055    2020    Spain             5              13                    7   
1056    2020    Spain             5              14                    6   
1057    2020    Spain             5              13                    6   

      matches_played_away  suspended_matches  ...  \
0                       6                  0  ...   
1                       7                  0  ...   
2                       6                  1  ...   
3                       6                  0  ...   
4                       7                  0  ...   
...                   ...                ...  ...   
1053                    5                  1  ...   
1054                    6                  2  ...   
1055                    6                  0  ...   
1056                    8                  0  ...   
1057                    7                  0  ...   

      goals_conceded_min_51_to_60  goals_conceded_min_61_to_70  \
0                               0                            0   
1                               2                            0   
2                               3                            1   
3                               0                            0   
4                               6                            5   
...                           ...                          ...   
1053                            1                            1   
1054                            4                            0   
1055                            5                            2   
1056                            3                            3   
1057                            2                            2   

      goals_conceded_min_71_to_80  goals_conceded_min_81_to_90  \
0                               4                            2   
1                               0                            7   
2                               2                            1   
3                               2                            4   
4                               1                            5   
...                           ...                          ...   
1053                            1                            3   
1054                            3                            1   
1055                            1                            4   
1056                            1                            7   
1057                            1                            3   

   

In [4]:
# Drop the null rows
df_null = soccer_data_df.dropna()
df_null

# No columns or rows were dropped so we can use our original data.

team_name  team_code           common_name  \
0                          Arsenal FC          1               Arsenal   
1                Tottenham Hotspur FC          2     Tottenham Hotspur   
2                  Manchester City FC          3       Manchester City   
3                   Leicester City FC          4        Leicester City   
4             West Bromwich Albion FC          5  West Bromwich Albion   
...                               ...        ...                   ...   
1053           Getafe Club de F?§tbol       1054             Getafe CF   
1054                         Elche CF       1055              Elche CF   
1055  Real Valladolid Club de F?§tbol       1056       Real Valladolid   
1056                        SD Huesca       1057             SD Huesca   
1057                        C?­diz CF       1058                C?­diz   

      season  country  country_code  matches_played  matches_played_home  \
0       2020  England             1              13                    7   
1       2020  England             1              13                    6   
2       2020  England             1              12                    6   
3       2020  England             1              13                    7   
4       2020  England             1              13                    6   
...      ...      ...           ...             ...                  ...   
1053    2020    Spain             5              12                    7   
1054    2020    Spain             5              12                    6   
1055    2020    Spain             5              13                    7   
1056    2020    Spain             5              14                    6   
1057    2020    Spain             5              13                    6   

      matches_played_away  suspended_matches  ...  \
0                       6                  0  ...   
1                       7                  0  ...   
2                       6                  1  ...   
3                       6                  0  ...   
4                       7                  0  ...   
...                   ...                ...  ...   
1053                    5                  1  ...   
1054                    6                  2  ...   
1055                    6                  0  ...   
1056                    8                  0  ...   
1057                    7                  0  ...   

      goals_conceded_min_51_to_60  goals_conceded_min_61_to_70  \
0                               0                            0   
1                               2                            0   
2                               3                            1   
3                               0                            0   
4                               6                            5   
...                           ...                          ...   
1053                            1                            1   
1054                            4                            0   
1055                            5                            2   
1056                            3                            3   
1057                            2                            2   

      goals_conceded_min_71_to_80  goals_conceded_min_81_to_90  \
0                               4                            2   
1                               0                            7   
2                               2                            1   
3                               2                            4   
4                               1                            5   
...                           ...                          ...   
1053                            1                            3   
1054                            3                            1   
1055                            1                            4   
1056                            1                            7   
1057                            1                            3   

   

In [5]:
soccer_data_df['Champion'] = np.where(soccer_data_df['league_position'] <= 4, "Champion", "Not")
soccer_data_df[['team_code','season','Champion']].head(200)

team_code  season  Champion
0            1    2020       Not
1            2    2020  Champion
2            3    2020       Not
3            4    2020  Champion
4            5    2020       Not
..         ...     ...       ...
195        196    2011       Not
196        197    2011       Not
197        198    2011       Not
198        199    2011       Not
199        200    2011       Not

[200 rows x 3 columns]

In [6]:
soccer_data_df = soccer_data_df.drop(['team_name','common_name','country'], axis=1)

In [7]:
soccer_data_df

team_code  season  country_code  matches_played  matches_played_home  \
0             1    2020             1              13                    7   
1             2    2020             1              13                    6   
2             3    2020             1              12                    6   
3             4    2020             1              13                    7   
4             5    2020             1              13                    6   
...         ...     ...           ...             ...                  ...   
1053       1054    2020             5              12                    7   
1054       1055    2020             5              12                    6   
1055       1056    2020             5              13                    7   
1056       1057    2020             5              14                    6   
1057       1058    2020             5              13                    6   

      matches_played_away  suspended_matches  wins  wins_home  wins_away  ...  \
0                       6                  0     4          2          2  ...   
1                       7                  0     7          3          4  ...   
2                       6                  1     5          3          2  ...   
3                       6                  0     8          3          5  ...   
4                       7                  0     1          1          0  ...   
...                   ...                ...   ...        ...        ...  ...   
1053                    5                  1     3          3          0  ...   
1054                    6                  2     3          1          2  ...   
1055                    6                  0     3          2          1  ...   
1056                    8                  0     1          1          0  ...   
1057                    7                  0     5          1          4  ...   

      goals_conceded_min_61_to_70  goals_conceded_min_71_to_80  \
0                               0                            4   
1                               0                            0   
2                               1                            2   
3                               0                            2   
4                               5                            1   
...                           ...                          ...   
1053                            1                            1   
1054                            0                            3   
1055                            2                            1   
1056                            3                            1   
1057                            2                            1   

      goals_conceded_min_81_to_90  draw_percentage_overall  \
0                               2                     0.15   
1                               7                     0.31   
2                               1                     0.42   
3                               4                     0.00   
4                               5                     0.31   
...                           ...                      ...   
1053                            3                     0.33   
1054                            1                     0.42   
1055                            4                     0.31   
1056                            7                     0.57   
1057                            3                     0.23   

      draw_percentage_home  draw_percentage_away  loss_percentage_ovearll  \
0                     0.14                  0.17                     0.54   
1                     0.33                  0.29                     0.15   
2                     0.33                  0.50                     0.17   
3                     0.00                  0.00                     0.38   
4                     0.33                  0.29                     0.62   
...                    ...                   ...                      ...   
1053               

In [8]:
soccer_data_df['season'].dtypes

dtype('int64')

In [9]:
soccer_data_ml_df = soccer_data_df[['team_code', 'season', 'country_code', 'Champion', 'wins_home', 'wins_away', 'average_possession', 'cards_per_match', 'clean_sheet_half_time_percentage_home', 'clean_sheet_percentage', 'corners_per_match', 'first_team_to_score_percentage', 'fouls', 'fts_half_time_percentage', 'fts_percentage', 'goals_conceded_per_match', 'goals_scored_per_match', 'leading_at_half_time_percentage', 'losing_at_half_time_percentage', 'shots', 'shots_on_target', 'goals_scored_min_0_to_10', 'goals_scored_min_11_to_20', 'goals_scored_min_21_to_30', 'goals_scored_min_31_to_40', 'goals_scored_min_41_to_50', 'goals_scored_min_51_to_60', 'goals_scored_min_61_to_70', 'goals_scored_min_71_to_80', 'goals_scored_min_81_to_90'
]]
soccer_data_ml_df.head(10)

team_code  season  country_code  Champion  wins_home  wins_away  \
0          1    2020             1       Not          2          2   
1          2    2020             1  Champion          3          4   
2          3    2020             1       Not          3          2   
3          4    2020             1  Champion          3          5   
4          5    2020             1       Not          1          0   
5          6    2020             1       Not          2          3   
6          7    2020             1       Not          3          4   
7          8    2020             1       Not          1          1   
8          9    2020             1  Champion          4          3   
9         10    2020             1       Not          1          6   

   average_possession  cards_per_match  clean_sheet_half_time_percentage_home  \
0                  54             1.92                                   0.43   
1                  50             1.23                                   1.00   
2                  64             1.42                                   0.50   
3                  54             2.15                                   0.43   
4                  42             1.77                                   0.83   
5                  41             1.69                                   0.50   
6                  50             1.92                                   0.33   
7                  41             1.25                                   0.40   
8                  55             1.46                                   0.83   
9                  54             1.75                                   0.67   

   clean_sheet_percentage  ...  shots_on_target  goals_scored_min_0_to_10  \
0                    0.23  ...               50                         1   
1                    0.38  ...               75                         5   
2                    0.42  ...               74                         3   
3                    0.31  ...               64                         1   
4                    0.15  ...               47                         2   
5                    0.08  ...               58                         3   
6                    0.23  ...               73                         2   
7                    0.42  ...               41                         3   
8                    0.38  ...               71                         2   
9                    0.25  ...               66                         1   

   goals_scored_min_11_to_20  goals_scored_min_21_to_30  \
0                          0                          3   
1                          3                          3   
2                          2                          5   
3                          2                          3   
4                          1                          3   
5                          3                          2   
6                          3                          3   
7                          0                          0   
8                          2                          2   
9                          0                          3   

   goals_scored_min_31_to_40  goals_scored_min_41_to_50  \
0                          0                          1   
1                          2                          3   
2                          2                          1   
3                          1                          3   
4                          0                          3   
5                          1                          1   
6                          3                          3   
7                          0                          0   
8                          5                          4   
9                          2                          1   

   goals_scored_min_51_to_60  goals_scored_min_61_to_70  \
0                          2                          3   
1                          1                          2   
2              

In [10]:
past_soccer_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2010) | (soccer_data_ml_df["season"] == 2011) | (soccer_data_ml_df["season"] == 2012) | (soccer_data_ml_df["season"] == 2013) | (soccer_data_ml_df["season"] == 2014) | (soccer_data_ml_df["season"] == 2015) | (soccer_data_ml_df["season"] == 2016) | (soccer_data_ml_df["season"] == 2017) | (soccer_data_ml_df["season"] == 2018) | (soccer_data_ml_df["season"] == 2019)]
past_soccer_df     

team_code  season  country_code  Champion  wins_home  wins_away  \
20           21    2019             1       Not         10          4   
21           22    2019             1       Not         12          4   
22           23    2019             1  Champion         15         11   
23           24    2019             1       Not         11          7   
24           25    2019             1       Not          6          5   
...         ...     ...           ...       ...        ...        ...   
1033       1034    2010             5       Not          3          3   
1034       1035    2010             5       Not          9          3   
1035       1036    2010             5       Not          9          3   
1036       1037    2010             5       Not          8          4   
1037       1038    2010             5       Not          7          2   

      average_possession  cards_per_match  \
20                    54             2.53   
21                    52             2.32   
22                    67             1.79   
23                    58             1.24   
24                    45             1.74   
...                  ...              ...   
1033                   0             2.84   
1034                   0             2.53   
1035                   0             3.58   
1036                   0             2.66   
1037                   0             2.89   

      clean_sheet_half_time_percentage_home  clean_sheet_percentage  ...  \
20                                     0.47                    0.26  ...   
21                                     0.53                    0.21  ...   
22                                     0.68                    0.45  ...   
23                                     0.63                    0.34  ...   
24                                     0.68                    0.26  ...   
...                                     ...                     ...  ...   
1033                                   0.42                    0.08  ...   
1034                                   0.63                    0.26  ...   
1035                                   0.42                    0.24  ...   
1036                                   0.63                    0.24  ...   
1037                                   0.53                    0.21  ...   

      shots_on_target  goals_scored_min_0_to_10  goals_scored_min_11_to_20  \
20                189                         5                          6   
21                199                         7                          3   
22                296                         6                          8   
23                224                         1                          6   
24                154                         0                          1   
...               ...                       ...                        ...   
1033              186                         8                          5   
1034              226                         2                          4   
1035              214                         4                          2   
1036              222                         1                          5   
1037              192                         2                          2   

      goals_scored_min_21_to_30  goals_scored_min_31_to_40  \
20                            6                          6   
21                           10                          7   
22                           14                          8   
23                            4                          8   
24                            3                          4   
...                         ...                        ...   
1033                          2                          2   
1034                          5                          5   
1035                          0                          7   
1036                          2                          7   
1037                          4                         

In [11]:
# Current league Position Leaders
current_soccer_league_leaders1_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 2))]
current_soccer_league_leaders2_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 4))]
current_soccer_league_leaders3_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 9))]
current_soccer_league_leaders4_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 11))]
current_soccer_league_leaders5_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 222))]
current_soccer_league_leaders6_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 223))]
current_soccer_league_leaders7_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 229))]
current_soccer_league_leaders8_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 231))]
current_soccer_league_leaders9_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 549))]
current_soccer_league_leaders10_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 553))]
current_soccer_league_leaders11_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 555))]
current_soccer_league_leaders12_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 560))]
current_soccer_league_leaders13_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 780))]
current_soccer_league_leaders14_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 781))]
current_soccer_league_leaders15_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 786))]
current_soccer_league_leaders16_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 793))]
current_soccer_league_leaders17_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1039))]
current_soccer_league_leaders18_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1041))]
current_soccer_league_leaders19_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1043))]
current_soccer_league_leaders20_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1052))]



### Split the Data into Training and Testing

In [12]:
# Create our features
X_train = past_soccer_df.drop("Champion",axis=1)
X_test1 = current_soccer_league_leaders1_df.drop("Champion",axis=1)
X_test2 = current_soccer_league_leaders2_df.drop("Champion",axis=1)
X_test3 = current_soccer_league_leaders3_df.drop("Champion",axis=1)
X_test4 = current_soccer_league_leaders4_df.drop("Champion",axis=1)
X_test5 = current_soccer_league_leaders5_df.drop("Champion",axis=1)
X_test6 = current_soccer_league_leaders6_df.drop("Champion",axis=1)
X_test7 = current_soccer_league_leaders7_df.drop("Champion",axis=1)
X_test8 = current_soccer_league_leaders8_df.drop("Champion",axis=1)
X_test9 = current_soccer_league_leaders9_df.drop("Champion",axis=1)
X_test10 = current_soccer_league_leaders10_df.drop("Champion",axis=1)
X_test11 = current_soccer_league_leaders11_df.drop("Champion",axis=1)
X_test12 = current_soccer_league_leaders12_df.drop("Champion",axis=1)
X_test13 = current_soccer_league_leaders13_df.drop("Champion",axis=1)
X_test14 = current_soccer_league_leaders14_df.drop("Champion",axis=1)
X_test15 = current_soccer_league_leaders15_df.drop("Champion",axis=1)
X_test16 = current_soccer_league_leaders16_df.drop("Champion",axis=1)
X_test17 = current_soccer_league_leaders17_df.drop("Champion",axis=1)
X_test18 = current_soccer_league_leaders18_df.drop("Champion",axis=1)
X_test19 = current_soccer_league_leaders19_df.drop("Champion",axis=1)
X_test20 = current_soccer_league_leaders20_df.drop("Champion",axis=1)

# X = pd.get_dummies(X)

# Create our target
y_train = past_soccer_df["Champion"]
y_test1 = current_soccer_league_leaders1_df["Champion"]
y_test2 = current_soccer_league_leaders2_df["Champion"]
y_test3 = current_soccer_league_leaders3_df["Champion"]
y_test4 = current_soccer_league_leaders4_df["Champion"]
y_test5 = current_soccer_league_leaders5_df["Champion"]
y_test6 = current_soccer_league_leaders6_df["Champion"]
y_test7 = current_soccer_league_leaders7_df["Champion"]
y_test8 = current_soccer_league_leaders8_df["Champion"]
y_test9 = current_soccer_league_leaders9_df["Champion"]
y_test10 = current_soccer_league_leaders10_df["Champion"]
y_test11 = current_soccer_league_leaders11_df["Champion"]
y_test12 = current_soccer_league_leaders12_df["Champion"]
y_test13 = current_soccer_league_leaders13_df["Champion"]
y_test14 = current_soccer_league_leaders14_df["Champion"]
y_test15 = current_soccer_league_leaders15_df["Champion"]
y_test16 = current_soccer_league_leaders16_df["Champion"]
y_test17 = current_soccer_league_leaders17_df["Champion"]
y_test18 = current_soccer_league_leaders18_df["Champion"]
y_test19 = current_soccer_league_leaders19_df["Champion"]
y_test20 = current_soccer_league_leaders20_df["Champion"]

### Balanced Random Forest Classifier

In [13]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
rf = BalancedRandomForestClassifier(n_estimators = 40, random_state=77)
rf = rf.fit(X_train, y_train)

### Tottenham Hotspur

In [14]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred1 = rf.predict(X_test1)
balanced_accuracy_score(y_test1, y_pred1)

1.0

In [15]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test1, y_pred1)

array([[1]], dtype=int64)

In [16]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test1, y_pred1))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Leicester City FC

In [17]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred2 = rf.predict(X_test2)
balanced_accuracy_score(y_test2, y_pred2)

0.0

In [18]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test2, y_pred2)

array([[0, 1],
       [0, 0]], dtype=int64)

In [19]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test2, y_pred2))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       1.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       0.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### Southampton FC

In [20]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred3 = rf.predict(X_test3)
balanced_accuracy_score(y_test3, y_pred3)

1.0

In [21]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test3, y_pred3)

array([[1]], dtype=int64)

In [22]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test3, y_pred3))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Liverpool FC

In [23]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred4 = rf.predict(X_test4)
balanced_accuracy_score(y_test4, y_pred4)

1.0

In [24]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test4, y_pred4)

array([[1]], dtype=int64)

In [25]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test4, y_pred4))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Olympique Lyonnais

In [26]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred5 = rf.predict(X_test5)
balanced_accuracy_score(y_test5, y_pred5)

1.0

In [27]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test5, y_pred5)

array([[1]], dtype=int64)

In [28]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test5, y_pred5))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Paris Saint-Germain FC

In [29]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred6 = rf.predict(X_test6)
balanced_accuracy_score(y_test6, y_pred6)

1.0

In [30]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test6, y_pred6)

array([[1]], dtype=int64)

In [31]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test6, y_pred6))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Lille OSC M'tropole

In [32]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred7 = rf.predict(X_test7)
balanced_accuracy_score(y_test7, y_pred7)

1.0

In [33]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test7, y_pred7)

array([[1]], dtype=int64)

In [34]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test7, y_pred7))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Olympique de Marseille

In [35]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred8 = rf.predict(X_test8)
balanced_accuracy_score(y_test8, y_pred8)

1.0

In [36]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test8, y_pred8)

array([[1]], dtype=int64)

In [37]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test8, y_pred8))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### BVB 09 Borussia Dortmund

In [38]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred9 = rf.predict(X_test9)
balanced_accuracy_score(y_test9, y_pred9)

0.0

In [39]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test9, y_pred9)

array([[0, 1],
       [0, 0]], dtype=int64)

In [40]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test9, y_pred9))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       1.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       0.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### FC Bayern Munchen

In [41]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred10 = rf.predict(X_test10)
balanced_accuracy_score(y_test10, y_pred10)

0.0

In [42]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test10, y_pred10)

array([[0, 1],
       [0, 0]], dtype=int64)

In [43]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test10, y_pred10))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       1.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       0.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### Bayer 04 Leverkusen

In [44]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred11 = rf.predict(X_test11)
balanced_accuracy_score(y_test11, y_pred11)

1.0

In [45]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test11, y_pred11)

array([[1]], dtype=int64)

In [46]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test11, y_pred11))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Rasen Ballsport Leipzig

In [47]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred12 = rf.predict(X_test12)
balanced_accuracy_score(y_test12, y_pred12)

1.0

In [48]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test12, y_pred12)

array([[1]], dtype=int64)

In [49]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test12, y_pred12))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Juventus FC

In [50]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred13 = rf.predict(X_test13)
balanced_accuracy_score(y_test13, y_pred13)

1.0

In [51]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test13, y_pred13)

array([[1]], dtype=int64)

In [52]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test13, y_pred13))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### AS Roma

In [53]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred14 = rf.predict(X_test14)
balanced_accuracy_score(y_test14, y_pred14)

0.0

In [54]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test14, y_pred14)

array([[0, 1],
       [0, 0]], dtype=int64)

In [55]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test14, y_pred14))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       1.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       0.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### AC Milan

In [56]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred15 = rf.predict(X_test15)
balanced_accuracy_score(y_test15, y_pred15)

1.0

In [57]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test15, y_pred15)

array([[1]], dtype=int64)

In [58]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test15, y_pred15))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### FC Internazionale Milano

In [59]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred16 = rf.predict(X_test16)
balanced_accuracy_score(y_test16, y_pred16)

0.0

In [60]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test16, y_pred16)

array([[0, 1],
       [0, 0]], dtype=int64)

In [61]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test16, y_pred16))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       1.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       0.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### Villarreal CF

In [62]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred17 = rf.predict(X_test17)
balanced_accuracy_score(y_test17, y_pred17)

0.0

In [63]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test17, y_pred17)

array([[0, 1],
       [0, 0]], dtype=int64)

In [64]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test17, y_pred17))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       1.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       0.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### Real Madrid CF

In [65]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred18 = rf.predict(X_test18)
balanced_accuracy_score(y_test18, y_pred18)

1.0

In [66]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test18, y_pred18)

array([[1]], dtype=int64)

In [67]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test18, y_pred18))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Club Atl??tico de Madrid

In [68]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred19 = rf.predict(X_test19)
balanced_accuracy_score(y_test19, y_pred19)

1.0

In [69]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test19, y_pred19)

array([[1]], dtype=int64)

In [70]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test19, y_pred19))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Real Sociedad de F?§tbol

In [71]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred20 = rf.predict(X_test20)
balanced_accuracy_score(y_test20, y_pred20)

1.0

In [72]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test20, y_pred20)

array([[1]], dtype=int64)

In [73]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test20, y_pred20))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



## Teams in league possitions 5 and worse

In [74]:
# Current league Position Leaders
current_soccer_league_leaders21_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 7))]
current_soccer_league_leaders22_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 565))]
current_soccer_league_leaders23_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 779))]
current_soccer_league_leaders24_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1040))]
current_soccer_league_leaders25_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 226))]
current_soccer_league_leaders26_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 10))]
current_soccer_league_leaders27_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 230))]
current_soccer_league_leaders28_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 558))]
current_soccer_league_leaders29_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 792))]
current_soccer_league_leaders30_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1042))]
current_soccer_league_leaders31_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 12))]
current_soccer_league_leaders32_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 236))]
current_soccer_league_leaders33_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 564))]
current_soccer_league_leaders34_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 795))]
current_soccer_league_leaders35_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1047))]
current_soccer_league_leaders36_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 13))]
current_soccer_league_leaders37_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 221))]
current_soccer_league_leaders38_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 554))]
current_soccer_league_leaders39_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 788))]
current_soccer_league_leaders40_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1058))]
current_soccer_league_leaders41_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 3))]
current_soccer_league_leaders42_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 232))]
current_soccer_league_leaders43_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 563))]
current_soccer_league_leaders44_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 787))]
current_soccer_league_leaders45_df = soccer_data_ml_df[(soccer_data_ml_df["season"] == 2020) & ((soccer_data_ml_df["team_code"] == 1049))]



### Split the Data into Training and Testing

In [75]:
# Create our features
X_test21 = current_soccer_league_leaders21_df.drop("Champion",axis=1)
X_test22 = current_soccer_league_leaders22_df.drop("Champion",axis=1)
X_test23 = current_soccer_league_leaders23_df.drop("Champion",axis=1)
X_test24 = current_soccer_league_leaders24_df.drop("Champion",axis=1)
X_test25 = current_soccer_league_leaders25_df.drop("Champion",axis=1)
X_test26 = current_soccer_league_leaders26_df.drop("Champion",axis=1)
X_test27 = current_soccer_league_leaders27_df.drop("Champion",axis=1)
X_test28 = current_soccer_league_leaders28_df.drop("Champion",axis=1)
X_test29 = current_soccer_league_leaders29_df.drop("Champion",axis=1)
X_test30 = current_soccer_league_leaders30_df.drop("Champion",axis=1)
X_test31 = current_soccer_league_leaders31_df.drop("Champion",axis=1)
X_test32 = current_soccer_league_leaders32_df.drop("Champion",axis=1)
X_test33 = current_soccer_league_leaders33_df.drop("Champion",axis=1)
X_test34 = current_soccer_league_leaders34_df.drop("Champion",axis=1)
X_test35 = current_soccer_league_leaders35_df.drop("Champion",axis=1)
X_test36 = current_soccer_league_leaders36_df.drop("Champion",axis=1)
X_test37 = current_soccer_league_leaders37_df.drop("Champion",axis=1)
X_test38 = current_soccer_league_leaders38_df.drop("Champion",axis=1)
X_test39 = current_soccer_league_leaders39_df.drop("Champion",axis=1)
X_test40 = current_soccer_league_leaders40_df.drop("Champion",axis=1)
X_test41 = current_soccer_league_leaders41_df.drop("Champion",axis=1)
X_test42 = current_soccer_league_leaders42_df.drop("Champion",axis=1)
X_test43 = current_soccer_league_leaders43_df.drop("Champion",axis=1)
X_test44 = current_soccer_league_leaders44_df.drop("Champion",axis=1)
X_test45 = current_soccer_league_leaders45_df.drop("Champion",axis=1)

# X = pd.get_dummies(X)

# Create our target
y_test21 = current_soccer_league_leaders21_df["Champion"]
y_test22 = current_soccer_league_leaders22_df["Champion"]
y_test23 = current_soccer_league_leaders23_df["Champion"]
y_test24 = current_soccer_league_leaders24_df["Champion"]
y_test25 = current_soccer_league_leaders25_df["Champion"]
y_test26 = current_soccer_league_leaders26_df["Champion"]
y_test27 = current_soccer_league_leaders27_df["Champion"]
y_test28 = current_soccer_league_leaders28_df["Champion"]
y_test29 = current_soccer_league_leaders29_df["Champion"]
y_test30 = current_soccer_league_leaders30_df["Champion"]
y_test31 = current_soccer_league_leaders31_df["Champion"]
y_test32 = current_soccer_league_leaders32_df["Champion"]
y_test33 = current_soccer_league_leaders33_df["Champion"]
y_test34 = current_soccer_league_leaders34_df["Champion"]
y_test35 = current_soccer_league_leaders35_df["Champion"]
y_test36 = current_soccer_league_leaders36_df["Champion"]
y_test37 = current_soccer_league_leaders37_df["Champion"]
y_test38 = current_soccer_league_leaders38_df["Champion"]
y_test39 = current_soccer_league_leaders39_df["Champion"]
y_test40 = current_soccer_league_leaders40_df["Champion"]
y_test41 = current_soccer_league_leaders41_df["Champion"]
y_test42 = current_soccer_league_leaders42_df["Champion"]
y_test43 = current_soccer_league_leaders43_df["Champion"]
y_test44 = current_soccer_league_leaders44_df["Champion"]
y_test45 = current_soccer_league_leaders45_df["Champion"]


## Teams Originally not predicted to be entering tournament

### Everton FC

In [76]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred21 = rf.predict(X_test21)
balanced_accuracy_score(y_test21, y_pred21)

0.0

In [77]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test21, y_pred21)

array([[0, 0],
       [1, 0]], dtype=int64)

In [78]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test21, y_pred21))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       0.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       1.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### 1. FC Union Berlin

In [79]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred22 = rf.predict(X_test22)
balanced_accuracy_score(y_test22, y_pred22)

0.0

In [80]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test22, y_pred22)

array([[0, 0],
       [1, 0]], dtype=int64)

In [81]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test22, y_pred22))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       0.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       1.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### SSC Napoli

In [82]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred23 = rf.predict(X_test23)
balanced_accuracy_score(y_test23, y_pred23)

1.0

In [83]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test23, y_pred23)

array([[1]], dtype=int64)

In [84]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test23, y_pred23))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### FC Barcelona

In [85]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred24 = rf.predict(X_test24)
balanced_accuracy_score(y_test24, y_pred24)

0.0

In [86]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test24, y_pred24)

array([[0, 0],
       [1, 0]], dtype=int64)

In [87]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test24, y_pred24))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       0.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       1.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### Montpellier HSC

In [88]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred25 = rf.predict(X_test25)
balanced_accuracy_score(y_test25, y_pred25)

1.0

In [89]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test25, y_pred25)

array([[1]], dtype=int64)

In [90]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test25, y_pred25))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Manchester United FC

In [91]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred26 = rf.predict(X_test26)
balanced_accuracy_score(y_test26, y_pred26)

1.0

In [92]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test26, y_pred26)

array([[1]], dtype=int64)

In [93]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test26, y_pred26))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Stade Rennais FC

In [94]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred27 = rf.predict(X_test27)
balanced_accuracy_score(y_test27, y_pred27)

1.0

In [95]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test27, y_pred27)

array([[1]], dtype=int64)

In [96]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test27, y_pred27))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### VfL Wolfsburg

In [97]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred28 = rf.predict(X_test28)
balanced_accuracy_score(y_test28, y_pred28)

1.0

In [98]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test28, y_pred28)

array([[1]], dtype=int64)

In [99]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test28, y_pred28))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### US Sassuolo Calcio

In [100]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred29 = rf.predict(X_test29)
balanced_accuracy_score(y_test29, y_pred29)

1.0

In [101]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test29, y_pred29)

array([[1]], dtype=int64)

In [102]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test29, y_pred29))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Sevilla FC

In [103]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred30 = rf.predict(X_test30)
balanced_accuracy_score(y_test30, y_pred30)

0.0

In [104]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test30, y_pred30)

array([[0, 0],
       [1, 0]], dtype=int64)

In [105]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test30, y_pred30))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       0.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       1.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### Chelsea FC

In [106]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred31 = rf.predict(X_test31)
balanced_accuracy_score(y_test31, y_pred31)

1.0

In [107]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test31, y_pred31)

array([[1]], dtype=int64)

In [108]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test31, y_pred31))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Racing Club de Lens

In [109]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred32 = rf.predict(X_test32)
balanced_accuracy_score(y_test32, y_pred32)

0.0

In [110]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test32, y_pred32)

array([[0, 0],
       [1, 0]], dtype=int64)

In [111]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test32, y_pred32))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       0.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       1.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### VfB Stuttgart 1893

In [112]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred33 = rf.predict(X_test33)
balanced_accuracy_score(y_test33, y_pred33)

1.0

In [113]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test33, y_pred33)

array([[1]], dtype=int64)

In [114]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test33, y_pred33))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Hellas Verona FC

In [115]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred34 = rf.predict(X_test34)
balanced_accuracy_score(y_test34, y_pred34)

1.0

In [116]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test34, y_pred34)

array([[1]], dtype=int64)

In [117]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test34, y_pred34))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Granada CF

In [118]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred35 = rf.predict(X_test35)
balanced_accuracy_score(y_test35, y_pred35)

1.0

In [119]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test35, y_pred35)

array([[1]], dtype=int64)

In [120]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test35, y_pred35))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### West Ham United FC

In [121]:
from sklearn.metrics import balanced_accuracy_score
y_pred36 = rf.predict(X_test36)
balanced_accuracy_score(y_test36, y_pred36)

1.0

In [122]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test36, y_pred36)

array([[1]], dtype=int64)

In [123]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test36, y_pred36))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### AS Monaco FC


In [124]:
from sklearn.metrics import balanced_accuracy_score
y_pred37 = rf.predict(X_test37)
balanced_accuracy_score(y_test37, y_pred37)

1.0

In [125]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test37, y_pred37)

array([[1]], dtype=int64)

In [126]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test37, y_pred37))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Borussia VfL M??nchengladbach


In [127]:
from sklearn.metrics import balanced_accuracy_score
y_pred38 = rf.predict(X_test38)
balanced_accuracy_score(y_test38, y_pred38)

1.0

In [128]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test38, y_pred38)

array([[1]], dtype=int64)

In [129]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test38, y_pred38))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Atalanta Bergamasca Calcio


In [130]:
from sklearn.metrics import balanced_accuracy_score
y_pred39 = rf.predict(X_test39)
balanced_accuracy_score(y_test39, y_pred39)

1.0

In [131]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test39, y_pred39)

array([[1]], dtype=int64)

In [132]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test39, y_pred39))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### C?­diz CF

In [133]:
from sklearn.metrics import balanced_accuracy_score
y_pred40 = rf.predict(X_test40)
balanced_accuracy_score(y_test40, y_pred40)

1.0

In [134]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test40, y_pred40)

array([[1]], dtype=int64)

In [135]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test40, y_pred40))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Manchester City FC

In [136]:
from sklearn.metrics import balanced_accuracy_score
y_pred41 = rf.predict(X_test41)
balanced_accuracy_score(y_test41, y_pred41)

0.0

In [137]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test41, y_pred41)

array([[0, 0],
       [1, 0]], dtype=int64)

In [138]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test41, y_pred41))

                   pre       rec       spe        f1       geo       iba       sup

   Champion       0.00      0.00      0.00      0.00      0.00      0.00       0.0
        Not       0.00      0.00      0.00      0.00      0.00      0.00       1.0

avg / total       0.00      0.00      0.00      0.00      0.00      0.00       1.0



### Angers Sporting Club de l'Ouest

In [139]:
from sklearn.metrics import balanced_accuracy_score
y_pred42 = rf.predict(X_test42)
balanced_accuracy_score(y_test42, y_pred42)

1.0

In [140]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test42, y_pred42)

array([[1]], dtype=int64)

In [141]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test42, y_pred42))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### FC Augsburg

In [142]:
from sklearn.metrics import balanced_accuracy_score
y_pred43 = rf.predict(X_test43)
balanced_accuracy_score(y_test43, y_pred43)

1.0

In [143]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test43, y_pred43)

array([[1]], dtype=int64)

In [144]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test43, y_pred43))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### SS Lazio

In [145]:
from sklearn.metrics import balanced_accuracy_score
y_pred44 = rf.predict(X_test44)
balanced_accuracy_score(y_test44, y_pred44)

1.0

In [146]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test44, y_pred44)

array([[1]], dtype=int64)

In [147]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test44, y_pred44))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1



### Athletic Club Bilbao

In [148]:
from sklearn.metrics import balanced_accuracy_score
y_pred45 = rf.predict(X_test45)
balanced_accuracy_score(y_test45, y_pred45)

1.0

In [149]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test45, y_pred45)

array([[1]], dtype=int64)

In [150]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test45, y_pred45))

                   pre       rec       spe        f1       geo       iba       sup

        Not       1.00      1.00      0.00      1.00      0.00      0.00         1

avg / total       1.00      1.00      0.00      1.00      0.00      0.00         1

